name: Monitor Stok Itemku
on:
  schedule:
    
cron: '0 * * * *' # Menjalankan script setiap 1 jam otomatis
workflow_dispatch:      # Tombol untuk jalankan manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      
uses: actions/checkout@v3
name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.9'
name: Install Libs
  run: pip install requests beautifulsoup4
name: Eksekusi Script
env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
run: python update_stok.py
