name: Monitor Stok Itemku

on:
  schedule:
    # Berjalan setiap 12 jam (Jam 00:00 dan 12:00 UTC)
    - cron: '0 */12 * * *'
  workflow_dispatch: # Agar tetap bisa dijalankan manual
  
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install library dan Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests
          playwright install chromium
          pip install pytz

      - name: Jalankan Script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python update_stok.py
